/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    events: Event;
    categories: Category;
    subscribers: Subscriber;
    leads: Lead;
    applications: Application;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Texte alternatif pour l’accessibilité et le SEO (obligatoire).
   */
  alt: string;
  caption?: string | null;
  /**
   * Crédit photo / source.
   */
  credit?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL de la page. Auto-généré depuis le titre si vide.
   */
  slug: string;
  /**
   * Page parente (pour la hiérarchie de menu).
   */
  parent?: (number | null) | Page;
  layout: (
    | {
        eyebrow?: string | null;
        heading: string;
        subheading?: string | null;
        image?: (number | null) | Media;
        cta?: {
          label?: string | null;
          href?: string | null;
        };
        variant?: ('image' | 'text' | 'split') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        width?: ('prose' | 'full') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        items?:
          | {
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        columns?: ('2' | '3') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureList';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        items?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats';
      }
    | {
        eyebrow?: string | null;
        quote: string;
        authorName: string;
        authorRole?: string | null;
        authorImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        items?:
          | {
              question: string;
              answer: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        heading: string;
        body?: string | null;
        buttons?:
          | {
              label: string;
              href: string;
              style?: ('primary' | 'secondary') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
  )[];
  seo?: {
    /**
     * Optimal : 50–60 caractères.
     */
    metaTitle?: string | null;
    /**
     * Optimal : 150–160 caractères.
     */
    metaDescription?: string | null;
    /**
     * Image utilisée pour le partage social (1200x630).
     */
    ogImage?: (number | null) | Media;
    /**
     * Empêcher l’indexation par les moteurs de recherche.
     */
    noIndex?: boolean | null;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL de la page. Auto-généré depuis le titre si vide.
   */
  slug: string;
  publishedAt?: string | null;
  category?: (number | null) | Category;
  coverImage?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    /**
     * Optimal : 50–60 caractères.
     */
    metaTitle?: string | null;
    /**
     * Optimal : 150–160 caractères.
     */
    metaDescription?: string | null;
    /**
     * Image utilisée pour le partage social (1200x630).
     */
    ogImage?: (number | null) | Media;
    /**
     * Empêcher l’indexation par les moteurs de recherche.
     */
    noIndex?: boolean | null;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  type: 'event' | 'post';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL de la page. Auto-généré depuis le titre si vide.
   */
  slug: string;
  startDate: string;
  endDate?: string | null;
  /**
   * Ex. CAD, 25 rue Roberts-Jones, Uccle
   */
  location?: string | null;
  category?: (number | null) | Category;
  coverImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URL externe d’inscription (Eventbrite, Google Form, …)
   */
  registrationUrl?: string | null;
  /**
   * Mettre en avant sur la home.
   */
  featured?: boolean | null;
  seo?: {
    /**
     * Optimal : 50–60 caractères.
     */
    metaTitle?: string | null;
    /**
     * Optimal : 150–160 caractères.
     */
    metaDescription?: string | null;
    /**
     * Image utilisée pour le partage social (1200x630).
     */
    ogImage?: (number | null) | Media;
    /**
     * Empêcher l’indexation par les moteurs de recherche.
     */
    noIndex?: boolean | null;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Abonnés à la newsletter (double opt-in). Exporter via les boutons Payload pour envoyer une campagne.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  profile: 'student' | 'professional' | 'parent' | 'other';
  status: 'pending' | 'active' | 'unsubscribed';
  locale?: ('fr' | 'en') | null;
  confirmToken?: string | null;
  unsubscribeToken?: string | null;
  confirmedAt?: string | null;
  unsubscribedAt?: string | null;
  /**
   * Traçabilité RGPD (consentement éclairé).
   */
  metadata?: {
    ip?: string | null;
    userAgent?: string | null;
    referrer?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Prospects qualifiés depuis le formulaire « I would like to… ». Conservation 2 ans max (RGPD).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  /**
   * Optionnel.
   */
  phone?: string | null;
  intents: ('brochure' | 'visit' | 'apply')[];
  desiredSection:
    | 'bachelor-interior'
    | 'bachelor-communication'
    | 'bachelor-fashion'
    | 'master-interior'
    | 'master-home-living'
    | 'master-digital-brand'
    | 'master-image'
    | 'master-event'
    | 'lifelong-genai'
    | 'undecided';
  profile: 'student' | 'parent' | 'professional' | 'other';
  /**
   * Message libre du prospect (optionnel).
   */
  message?: string | null;
  status: 'new' | 'contacted' | 'enrolled' | 'archived';
  locale?: ('fr' | 'en') | null;
  /**
   * Consentement éclairé (RGPD).
   */
  consent: {
    acceptedTerms: boolean;
    ip?: string | null;
    userAgent?: string | null;
    referrer?: string | null;
  };
  /**
   * Notes internes admissions (non visible par le prospect).
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Candidatures de pré-inscription formelles. Suivi par l’équipe Admissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  birthDate: string;
  nationality: string;
  address?: {
    street?: string | null;
    postalCode?: string | null;
    city?: string | null;
    country?: string | null;
  };
  desiredProgram:
    | 'bachelor-interior'
    | 'bachelor-communication'
    | 'bachelor-fashion'
    | 'master-interior'
    | 'master-home-living'
    | 'master-digital-brand'
    | 'master-image'
    | 'master-event';
  startYear: '2026' | '2027';
  startLevel: 'bac1' | 'bac2' | 'bac3' | 'm1' | 'm2';
  academic?: {
    currentSchool?: string | null;
    lastDiploma?: string | null;
    lastDiplomaYear?: number | null;
  };
  /**
   * Pourquoi le CAD ? Pourquoi ce programme ? Que voulez-vous y trouver ? (5–10 lignes suffisent.)
   */
  motivation: string;
  /**
   * URL de votre portfolio en ligne (Behance, Instagram, site perso, Google Drive). Optionnel à ce stade.
   */
  portfolioUrl?: string | null;
  source?: ('search' | 'word-of-mouth' | 'social' | 'event' | 'press' | 'alumni' | 'other') | null;
  status:
    | 'new'
    | 'reviewing'
    | 'interview-scheduled'
    | 'interview-done'
    | 'accepted'
    | 'enrolled'
    | 'rejected'
    | 'withdrawn';
  locale?: ('fr' | 'en') | null;
  /**
   * Consentement éclairé (RGPD).
   */
  consent: {
    acceptedTerms: boolean;
    ip?: string | null;
    userAgent?: string | null;
    referrer?: string | null;
  };
  /**
   * Notes internes Admissions (non visible par le candidat).
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              image?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        featureList?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              eyebrow?: T;
              quote?: T;
              authorName?: T;
              authorRole?: T;
              authorImage?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  category?: T;
  coverImage?: T;
  excerpt?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  category?: T;
  coverImage?: T;
  description?: T;
  registrationUrl?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  profile?: T;
  status?: T;
  locale?: T;
  confirmToken?: T;
  unsubscribeToken?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  metadata?:
    | T
    | {
        ip?: T;
        userAgent?: T;
        referrer?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  intents?: T;
  desiredSection?: T;
  profile?: T;
  message?: T;
  status?: T;
  locale?: T;
  consent?:
    | T
    | {
        acceptedTerms?: T;
        ip?: T;
        userAgent?: T;
        referrer?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  birthDate?: T;
  nationality?: T;
  address?:
    | T
    | {
        street?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  desiredProgram?: T;
  startYear?: T;
  startLevel?: T;
  academic?:
    | T
    | {
        currentSchool?: T;
        lastDiploma?: T;
        lastDiplomaYear?: T;
      };
  motivation?: T;
  portfolioUrl?: T;
  source?: T;
  status?: T;
  locale?: T;
  consent?:
    | T
    | {
        acceptedTerms?: T;
        ip?: T;
        userAgent?: T;
        referrer?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        path: string;
        children?:
          | {
              label: string;
              path: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    path?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * Chemin interne (ex: '/about') ou URL externe (ex: 'https://...').
               */
              path: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legal?:
    | {
        label: string;
        path: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  contact?: {
    address?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  social?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'vimeo' | 'behance';
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        path?: T;
        children?:
          | T
          | {
              label?: T;
              path?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        path?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              path?: T;
              id?: T;
            };
        id?: T;
      };
  legal?:
    | T
    | {
        label?: T;
        path?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  contact?:
    | T
    | {
        address?: T;
        email?: T;
        phone?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}